### ISSUE TITLE
ci(github): pod: not found

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/monsuivipsy#72]
It seems like we have an issue with a postinstall @tangimds 

```
$ pod install --project-directory=ios/ --repo-update && npx jetify -r
/bin/sh: line 1: pod: command not found
```
https://github.com/SocialGouv/monsuivipsy/runs/3115049148

Do you know what to do ?

**Comment by tangimds** [comment]
Hello, why did we add CI on github ? (on peut parlé francais si tu veux :) )

**Comment by douglasduteil** [comment]
C'est toujours bon d'avoir une CI qui confirme l'état du code hors de nos machine respective ;)
